formulaire modif données perso
Escadev-SLDN2/hotel_nice pull request #33
Opened 2020-03-25 11:23 UTC by GermainA

2020-03-25 15:08 UTC, DesirThomas requested changes

2020-03-25 15:08 UTC, DesirThomas commented on formulaire_modification.html
> +                        <label for="firstName">Ancienne adresse mail :*</label>
Je crois que j'ai oublié ce détail aussi sur ma PR, je vais aller vérifier ensuite, mais il nous faudrait modifier le type, l'id, et le name des labels et input afin qu'il soit plus représentatif des champs demandés.

label : for="oldMail"

2020-03-25 15:08 UTC, DesirThomas commented on formulaire_modification.html
> +                        <input type="text" id="firstName" name="firstName" required>
input : type ="mail" id="oldMail" name ="oldMail"

2020-03-25 15:08 UTC, DesirThomas commented on formulaire_modification.html
> +                        <label for="lastName">Nouvelle adresse mail :*</label>
newMail

2020-03-25 15:08 UTC, DesirThomas commented on formulaire_modification.html
> +                        <input type="text" id="lastName" name="lastName" required>
mail ; newMail ; newMail

2020-03-27 13:46 UTC, Bastien-Baloup approved these changes

2020-03-27 13:46 UTC, camille-avignon approved these changes

2020-03-27 13:47 UTC, ghost approved these changes

2020-03-27 13:52 UTC, DesirThomas approved these changes

2020-03-27 13:54 UTC, merged