code revu
Escadev-SLDN2/hotel_nice pull request #38
Opened 2020-05-18 10:04 UTC by GermainA

2020-05-18 10:14 UTC, Bastien-Baloup requested changes
Il faut copier les changements de index.php vers index_en.php

2020-05-19 08:02 UTC, Bastien-Baloup approved these changes

2020-05-19 08:05 UTC, camille-avignon approved these changes

2020-05-19 08:08 UTC, CBaraka approved these changes

2020-05-19 08:31 UTC, merged